### ISSUE TITLE
Is it possible to train and predict a per-atom property? [question]

### ISSUE THREAD

**Issue by UnixJunkie** [lab-cosmo/librascal#407]
Hello,

I'd like to give a try at librascal and SOAP features (probably using GPR).
While reading librascal/examples/needs_updating/Precition_example.ipynb;
I understand that you train/test using a property for each molecule.

I wonder if it possible to train/test using a property per atom of the molecule;
instead of a property for the whole molecule.

Would you have some example for that?

Thanks a lot,
Francois.

**Comment by UnixJunkie** [comment]
If the related librascal/examples/needs_updating/Precition_example.ipynb could be updated
to work, it would be nice.
I'll try getting an older version of librascal where it can run, in the meantime.

**Comment by max-veit** [comment]
Hi Francois,

Yes, you can use librascal to predict per-atom properties. Basically, you just need to create a `Kernel` object with `target_type=='Atom'` (instead of `target_type=='Structure'`). You can then use the resulting kernel to do GPR in an atom-wise way, somewhat similar to what is shown in `Prediction_example.ipynb` as you mentioned. The fitting/prediction itself should also be possible with librascal's `train_gap_model()` function*, with the appropriately created kernel object passed in.

As for the `Prediction_example.ipynb` notebook, indeed, it is quite out of date; I would recommend instead to follow the `zundel_i-PI.ipynb` example (but using atom-wise kernels and properties as mentioned above, and without forces/gradients). But thank you for the feedback; we'll see if we can make a more general example that includes training atom-wise properties.

Hope this helps,
Max

[*] note that this function is due to be replaced by a simplified version in #305, though the replacement will still support fitting with per-atom properties.
